# Generated by Django 6.0 on 2025-12-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=200)),
                ('parent_institute', models.CharField(blank=True, default='', max_length=200)),
                ('response_to_course', models.CharField(blank=True, default='', max_length=200)),
                ('city', models.CharField(blank=True, default='', max_length=100)),
                ('locality', models.CharField(blank=True, default='', max_length=100)),
                ('student_state', models.CharField(blank=True, default='', max_length=100)),
                ('student_city', models.CharField(blank=True, default='', max_length=100)),
                ('current_locality', models.CharField(blank=True, default='', max_length=100)),
                ('response_date', models.DateTimeField(blank=True, null=True)),
                ('response_type', models.CharField(blank=True, default='', max_length=100)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('isd_code', models.CharField(blank=True, default='', max_length=10)),
                ('mobile', models.CharField(blank=True, default='', max_length=15)),
                ('is_in_ndn_list', models.CharField(blank=True, default='', max_length=10)),
                ('exams_taken', models.CharField(blank=True, default='', max_length=100)),
                ('student_work_experience', models.CharField(blank=True, default='', max_length=100)),
                ('response_to_course_program', models.CharField(blank=True, default='', max_length=200)),
                ('total_responses_course_parent', models.IntegerField(default=0)),
                ('total_responses_course_program', models.IntegerField(default=0)),
                ('total_responses_course', models.IntegerField(default=0)),
            ],
        ),
    ]
