# Generated by Django 6.0 on 2025-12-31 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentrecord',
            name='course',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='total_responses_course',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='total_responses_course_parent',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='studentrecord',
            name='total_responses_course_program',
            field=models.CharField(blank=True, default='0', max_length=50),
        ),
    ]
